app:
  secret_key: "my-secret"
certs:
  private_key: 
    path: ${APP_PATH}/certs/private-key.pem
  public_key: 
    path: ${APP_PATH}/certs/public-key.pem
logging:
  config:
    path: ${APP_PATH}/default_logging.ini
postgres:
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  host: ${POSTGRES_HOST}
  db_name: ${POSTGRES_DB}
  port: ${POSTGRES_PORT}
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
