name: run python tests

on:
  push:
    branches:
      - '*'
        
jobs:
  tests:
    strategy:
      matrix: { service: ['./tirelire-account', './tirelire-auth', './tirelire-ml-cat-operation', './tirelire-web-backend'] }
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.10
      - name: Set up postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.12
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install library and test ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: |
          poetry install
          source .venv/bin/activate
          poetry run test
          poetry run report
