name: run python tests

on:
  push:
    branches:
      - 'master'
        
jobs:
  tests:
    strategy:
      max-parallel: 1
      matrix: { service: ['./tirelire-account', './tirelire-auth', './tirelire-ml-cat-operation', './tirelire-web-backend'] }
    env:
      RUNNER_ALLOW_RUNASROOT: 1
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '12'
      - name: Start Redis
        run: sudo apt-get install -y redis-tools redis-server
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.10
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.12
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install library and test ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: |
          poetry install
          source .venv/bin/activate
          poetry run test
          poetry run report
